### ISSUE TITLE
Throughput degradation when putting more requests

### ISSUE THREAD

**Issue by Cha465** [IBM/uDepot#8]
Thank you for previous answers! I can run udepot-test with trt_spdk backend now. However when testing I found something curious; simply putting 10M requests yields a tput of 5Mops, saturating all the SSDs, but putting 120M requests degrades it to 1.37Mops. Any luck that something can explain this? (I ran udepot-test with `./udepot-test -f PHAL1241002Z400AGN,PHAL111100PB400AGN,PHAL12460040400AGN,PHAL2023005P400BGN,PHAL1442000Y400AGN -w 10000000 -t 24 --grain-size 4096 --val-size 3072 -u 8 --thin --zero-copy --force-destroy`)

**Comment by nik-io** [comment]
This might have to do with the amount of dynamic table grows required to fit the larger dataset. The default table size is equal to a single segment, which defaults to 512MiB, I believe https://github.com/IBM/uDepot/blob/5b9d9f4c559c76f0d02f65a3dc300b665138cd0b/src/include/uDepot/udepot-lsa.hh#L37
You can try increasing that to 1 or 2 GiB and see if it helps. 
Another thing that might affect performance could be the contention on the hash table. You can check if that’s the case if you run single thread mode and the performance issue goes away. In that case, you could increase the number of hash table locks. 
If none of the above work, then I suggest to try different, growing combinations of thread count and trt-tasks parameter (per thread task parallelism) and see how they scale for the different test sizes. These should help identify where the problem is.

**Comment by Cha465** [comment]
Thanks! Found out that load imbalance caused this (I have modified workload distribution to zipfian and used customized network stack).
